### ISSUE TITLE
Reading speed & cadence

### ISSUE THREAD

**Issue by dhague** [clivemjeffery/qbike#1]
Hi Clive,

Just to let you know that over the holidays I implemented [some code](https://github.com/dhague/vpower) to read speed/cadence and write power (based on turbo power curves). Feel free to use it as a basis for your project.

Cheers,
Darren

**Comment by clivemjeffery** [comment]
Thanks Darren,

Your project looks really interesting and I'll take a good look during the next holiday. It happens that I did get a Pi Zero for Christmas but right now I only have training rollers. I wonder if there is any useful relation between speed and power on rollers?

Clive.

**Comment by PeterGamma** [comment]
Hi Clive, your project is great.  And also Darren Hague s project, althoug I did not test it yet, since I am a Rasperri PI greenhorn. I don t know whether there is a difference between power on rollers or not on rollers. But here is what I found out about relatio between speed an power:

How does speed affect power?

«It turns out that an object's kinetic energy increases as the square of its speed. A car moving 40 mph has four times as much kinetic energy as one moving 20 mph, while at 60 mph a car carries nine times as much kinetic energy as at 20 mph. Thus a modest increase in speed can cause a large increase in kinetic energy.»

source:

http://www.auburn.edu/academic/classes/scmh/1010/Kinetic%20Energy.php

would be great if we become a community of Rasperri ANT+ developers:

https://petergamma.org/what-can-we-do-with-captured-ant-data/
